import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar'
import Land from '@/components/Land'
import { motion } from "framer-motion";
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const variantimage1 = {
    hidden: {
        
        scale: 1,
        x: 0,
      y:"-10vh",
    },
    visible: {
       
        scale: 1,
        x: 0,
        y: 0,
      transition: {
        type: "spring",
        stiffness: 10,
        duration: 3,
      },
    },
    exit: {
        rotate: 90,
        scale: 1,
        x: "22vw",
        y: "120vh",
        transition: {
          type: "spring",
          stiffness: 10,
          duration: 1,
        },
      },
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white w-full h-full'>
      <motion.div 
                        initial="hidden" // use variants to define initial and animate properties
                        animate="visible"
                         variants={variantimage1}> 
          <Navbar/>
      </motion.div> 
      <Land/>
        
      </main>
    </>
  )
}
